import sqlite3
import re
from pathlib import Path

DB = Path.home() / "vasuki" / "data" / "vasuki.db"

conn = sqlite3.connect(DB)
cur = conn.cursor()

patterns = [
    ("employment", r"offer letter|appointment letter|joining letter", 0.95),
    ("salary", r"payslip|salary", 0.90),
    ("resume", r"resume|curriculum vitae|cv", 0.90),
    ("education", r"certificate|degree|university|college", 0.80),
    ("banking", r"account statement|bank statement", 0.85),
    ("government", r"passport|aadhaar|pan card", 0.95),
]

cur.execute("""
SELECT file_path, content
FROM extracted_text
""")

rows = cur.fetchall()

added = 0

for file_path, content in rows:

    if not content:
        continue

    text = content.lower()

    year_match = re.search(r"(20[0-9]{2})", text)
    year = year_match.group(1) if year_match else "unknown"

    for event_type, pattern, confidence in patterns:

        if re.search(pattern, text):

            title = f"{event_type.upper()} detected in {Path(file_path).name}"

            cur.execute("""
            INSERT INTO timeline_events(
                event_date,
                event_type,
                title,
                source_path,
                confidence,
                notes
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """, (
                year,
                event_type,
                title,
                file_path,
                confidence,
                "Auto-generated by timeline_builder"
            ))

            added += 1
            break

conn.commit()

print(f"Timeline events added: {added}")

conn.close()
